### ISSUE TITLE
Implement pre-audit checklist for the current scope

### ISSUE THREAD

**Issue by azat-hafizov** [nutsfinance/tapio-eth#24]
Guide to ensure Tapio contracts meet standards and best practices before we go into the next audit

- [x] Using industry-known libraries where possible (at least OZ)
- [x] Avoid using inline assembly where possible
- [x] Latest major Solidity version
- [ ] Document functions (at least external/public)
- [ ] Tapio security assumptions declared to auditors
- [ ] Intentionally negative tests to expect breaking if required
- [ ] Checks/effects/interactions pattern
- [ ] Basic fuzz testing (Foundry) and static analysis (Slither)
- [ ] Basic inheritance graphs and core UML diagrams
